### ISSUE TITLE
What pins do I connect?

### ISSUE THREAD

**Issue by Darker** [MarcelMG/AVR8_BitBang_UART_TX#2]
I cannot figure out which pins are represented by the constants in the code:

```
// change these to use another pin
#define TX_PORT PORTB
#define TX_PIN  PB0
#define TX_DDR  DDRB
#define TX_DDR_PIN DDB0
```

I cannot find where are they defined.

**Comment by MarcelMG** [comment]
There is only one pin defined here.
The physical pin is TX_PIN, which is PB0. The other 3 defines have to be changed accordingly if you change the pin. Let's say e.g. you want to use pin PA2, then you define TX_PORT as PORT**A** (because pin P**A**2 is on port A), TX_DDR as DDR**A** and TX_DDR_PIN as DD**A2**. So only the letters in bold are changed.

Maybe if you come from the Arduino-world you don't know the principles of GPIO manipulation of the AVR. There are many tutorials you can find that explain how it works, and it's also useful to have a look at the datasheet of the microcontroller. There you'll find the names of the registers and bits as they're defined in *avr-libc*
